### ISSUE TITLE
How to add validation for <text> <select> <checkbox> html?

### ISSUE THREAD

**Issue by JeremyColton** [Albert-Gao/veasy#16]
Hi, great framework, thanks so much!

I see that you have validation that can be used for RadioButton and TextInput components.

What about other common html (text, select, checkbox) tags?

**Comment by Albert-Gao** [comment]
Yes, `veasy` could handle all of these.

After all, `veasy` only look for the `React` elements which have the `name` which has been listed in the `schema`. :)

**Comment by JeremyColton** [comment]
The easiest way to ensure, state, updates and error text is properly managed by your validation framework would be to create a TextAreaInput.js, Select.js (one per html tag) etc. files based on your TextInput.js file?

I can't see how to wire up the simple html tag (<textarea>, <select> etc.) to your validation framework...

**Comment by Albert-Gao** [comment]
## 1. 1st
> I can't see how to wire up the simple html tag (<textarea>, etc.) to your validation framework...

You can't.
Because `veasy` will ignore all the `html tag` intentionally.
Why? Because all the 3 `props` that `veasy` will inject to your components: `status`, `errorText` and `value`, they are not valid HTML attribute. Even `veasy` willing to bind them to plain HTML tag, `React` will give you error at runtime.

And without creating your own component, how could you switch the style based on the `status` and showing the `errorText`? :)

## 2. 2nd
> The easiest way to ensure, state, updates and error text is properly managed by your validation framework would be to create a TextAreaInput.js, Select.js (one per html tag) etc. files based on your TextInput.js file?

My `TextInput.js` is just to show how to use `veasy` with your component, there are multiple ways to create your own component, You don't need to use my code, as long as your component could consume that 4 `props` (`status, value, errorText and onChange`), you are good to go. :)

**Comment by JeremyColton** [comment]
Ok, thank you so much.
