### ISSUE TITLE
Editing text causes cursor to jump to end of field value

### ISSUE THREAD

**Issue by JeremyColton** [Albert-Gao/veasy#18]
I am using your example at:
https://github.com/Albert-Gao/veasy/tree/master/example

I found a bug. To re-create it:
1. Add some text to the 1st field, eg "admin@aaa.com"
2. Place your cursor after the 'n' and type '1'.

The '1' is added but then the cursor jumps to the end of the email address. So I can't keep editing from part-way thru the text field.

Please can you check this.

**Comment by Albert-Gao** [comment]
Thanks for reporting this.

A quick and by far the simplest fix for this:

When you bind the `value` to the `Input` component. Bind it to `defaultValue` rather than `value`. It will solve the issue. And validation of `veasy` still works.

For instance:

```xml
// Do this:
<TextInput defaultValue={this.props.value}>

// Not do this:
<TextInput value={this.props.value}>
```

Related discussion on [Repo of React](https://github.com/facebook/react/issues/955#issuecomment-281802381)

**Comment by Albert-Gao** [comment]
We should make this issue open because I'm not quite happy with this approach. But as far as I can see, this should be handled at the component level.

A potential change from `veasy` side:

At the very 1st release of `veasy`, it will auto-bind the `value, onChange and onBlur` for the user, but I took it out later on because `React` expects to bind all of these explicitly when you use `prop-types`. Otherwise, it will display a warning. 

Maybe we could use this, so the user could do less code at the component level, and `veasy` could handle case like this as well.

**Comment by JeremyColton** [comment]
I'm confused, in your example app.js there's no value set on the <TextInput>:
<TextInput name="title" placeholder="Put your title here"/>

Should there be a value bound here?

Regarding the second solution, I recommend the least confusing approach... :)

**Comment by Albert-Gao** [comment]
Yes, because it doesn't happen there.

I didn't bind the `value` in `App.js` because it has been auto-bind by the `VeasyForm`, in the `TextInput.js`, the actual binding happens there. See the `value={value}` at line 22.

The flow is:

1. `VeasyForm` auto-binds the `prop` to your component. 
1. Your component then uses that `prop`. And if you need to bind that `prop` to a component or a html tag. You still need to bind it.

And my bad, I think we can't do that in the `veasy` level, because it can't change the internal implementation of your component.

I think I will just add a new QA to the documentation. Or a PR will be appreciated :)

**Comment by JeremyColton** [comment]
So what is the preferred fix?

**Comment by Albert-Gao** [comment]
See my [comment](https://github.com/Albert-Gao/veasy/issues/18#issuecomment-350632771) before :)

**Comment by JeremyColton** [comment]
Ok, thanks :)

**Comment by JeremyColton** [comment]
This fix causes bug #24 so we need to keep this for setting an input's value:
<TextInput value={this.props.value}>

Is there another fix for this cursor-jumping bug?

**Comment by Albert-Gao** [comment]
This is really not a concern in terms of `Veasy`, because it's in the consumer's layer. But consider that you are a long time user and this troubles you so much. Gonna save you out of this :D

OK. @JeremyColton Here you go.

Check this commit  [aa1afcf](https://github.com/Albert-Gao/veasy/commit/aa1afcf81e11c5c8a37835e679f5d4afd095e1c4)

It should solve all the problems.

You just need to copy the `BaseInput.js` to your code base, and use it as the normal `input`.

- No more `defaultValue` workaround.
- `Reset` works as normal
- No more `cursor jumping`
- Still controlled component

Please check :)

Maybe we should include this in the next `Veasy` distribution.

**Comment by JeremyColton** [comment]
Thank you so much for your time on this. I've been very busy today to check it, I'll check tonight and update you asap.

**Comment by Albert-Gao** [comment]
Glad it helps! Thanks for your time. :)
