### ISSUE TITLE
Disable field validation until field loses focus

### ISSUE THREAD

**Issue by JeremyColton** [Albert-Gao/veasy#20]
Hi, the validation runs on every keystroke so the error message is always seen on every form field. The field content will be invalid until the users finishes typing.  So is it possible to delay the field's validation until the field loses focus?

**Comment by Albert-Gao** [comment]
I'm not quite sure your requirement. Do you meam that you wanna trigger the validation only when onBlur rather than onChange?

Because when the user is typing, the partial message could be wrong, but it's not the final state of that field because the user hasn't finish typing?

You can simply not binding the onChange for that component.

:)

**Comment by JeremyColton** [comment]
Hi, yes, I only want to trigger the validation when onBlur is called.  If I comment out the 'onchange={onChange} in the <TextInput> component then typing in the field does nothing:

`        <div className="validation">
            <input
                type={type}
                id={name}
                name={name}
                className={status}
                placeholder={placeholder}
                value={value}
                /*onChange={onChange}*/
                disabled={disabled}
                autoFocus={autoFocus}
                ref={ref}
            />
            <p className={errorText == '' ? 'hidden' : ''}>{errorText}</p>
        </div>`

How can I allow the field to accept input without this onChange handler?

**Comment by JeremyColton** [comment]
In conjuction with binding the value to 'defaultValue' instead of 'value', this works :)

So the <TextInput> component's <div> (from your TextInput.js file) looks like this:

`        <div className="validation">
            <input
                type={type}
                id={name}
                name={name}
                className={status}
                placeholder={placeholder}
                defaultValue={value}
                /*onChange={onChange}*/
                disabled={disabled}
                autoFocus={autoFocus}
                ref={ref}
            />
            <p className={errorText == '' ? 'hidden' : ''}>{errorText}</p>
        </div>`

This works. Many thanks.

**Comment by JeremyColton** [comment]
Previously, I used:
value={value}

And when I wanted to update a field's value in code, I would do:
this.setState({email:{value:''}})

But with the change above:
defaultValue={value}

- I can no longer update the field's value using:
this.setState({email:{value:''}})

How do I update this field's state programmatically?

**Comment by JeremyColton** [comment]
The form's submit button is disabled until the isFormOk = true.  By removing the onChange handler, each form field is only validated when onBlur is called. This means I need to:
1.  click once outside the form field for it to be validated and enable the submit button and 
2. click a second time on the button to submit the form.

So i've realised that the onChange handler needs to remain. BUT, only show any relevant validation message when the related form field's onBlur is called.

Apologies for this use-case, but is this possible?

**Comment by Albert-Gao** [comment]
> How do I update this field's state programmatically when I use defaultValue={value} when creating the component?

There are hacky ways if you google this. But allow me to answer this question along with the one below.

> So i've realised that the onChange handler needs to remain. BUT, only show any relevant validation message when the related form field's onBlur is called. Apologies for this use-case, but is this possible?

I think the original way is better, think of this use case, if you don't handle the `onChange`, or only show the error message when `onBlur` happens even `onChange` triggers before it. There is no way for the user to know whether his input is right or wrong unless he changes the focus.

Which means when the user at the last field, after he finishes entering the content.

He wants to click the submit button right after entering content.

But if he gets the wrong input, the submit button will be disabled and he can't click, but he doesn't know what is wrong there, because the `onBlur` hasn't been trigger yet.

Now this becomes confusing for the user. Why I can't click the submit button while there are no errors?

So, I recommend the original way which is been used by most of the site there.
Let me know if you have a use-case which isn't been covered. :)

**Comment by JeremyColton** [comment]
Ok, I agree that the onChange must stay as you have described. Many thanks.

Regarding the previous question - How do I update this field's state programmatically when I use defaultValue={value} when creating the component? ...I didn't see your answer to this...

**Comment by Albert-Gao** [comment]
@JeremyColton Sorry for the wait. 

What about you can add a new function to your schema to declare things you want to happen `after` or `before` the validation?

let's say for the `name` field,

```javascript
{
    "name": {
        "beforeValidation": function (value) {}
        "afterValidation": function (value) { }
    }
}
```

Then `veasy` will invoke these functions at the according time, will this solve your problem? :)

**Comment by JeremyColton** [comment]
Hey, sorry for the delay. I kept the onChange handler in the end.  But any additional functionality that you add can only increase your framework's usefulness :) I'll happily test it for you.

How do I update a field's state programmatically? eg reset a single field?
