### ISSUE TITLE
Do not display validation message when onChange/blur fire and field is empty

### ISSUE THREAD

**Issue by JeremyColton** [Albert-Gao/veasy#31]
If the user hasn't entered anything in a field then no need to tell him/her about it if they click outside the field and onchange/blur fire.  Facebook don't show a validation message if the login fields are left empty. 

Can the ability to run the validation in this scenario be configurable? Eg `runValidationOnEmptyField: true/false` [default can be true]

If the user enters something that doesn't meet the field's rules and onChange/blur fire, then show the validation message.

Your thoughts?

**Comment by Albert-Gao** [comment]
Then 1.7.0 behaves exactly like this. :(

**Comment by JeremyColton** [comment]
This isn't realated to `onlyWhen` unless I've missed something :( Can you provide a schema example from v1.7.0 that allows this?

**Comment by Albert-Gao** [comment]
Use 1.7.0. As described in this https://github.com/Albert-Gao/veasy/issues/30#issuecomment-387099064 .

Leaves `title` empty, then even you types something in `description` field, and it meets `onlyWhen` in `title`, it won't trigger validation for `onlyWhen` because it's empty, but everytime you type in `title`, validation will be triggered.

You need `isRequired` for `1.7.0`, but not required for `1.7.1` because now `onlyWhen` will let the field be validated everytime the other fields get validated to make sure the `isFormOK` shows the current situation.

**This behaviour only works for rule with `onlyWhen`.**

**Comment by JeremyColton** [comment]
Thanks for the clarification on the `isRequired` field with `onlyWhen`.

I apologise, but perhaps I didn't explain myself clearly, but this feature request is not related to inter-dependent fields (ie `onlyWhen`).

In its simplest use-case, there's a single field in the schema. The schema below requires the single description to be a min of 5 chars:
```
this.formSchema = {
            description: { minLength: [5, 'Must be min of 5 chars'] }
        };
```
When a user clicks in the field and then clicks on another part of the screen causing the onBlur event to fire, Veasy shows the validation message. But since the user hasn't typed anything, there's no need to show the message. If the user had typed 'abc' and then caused the onBlur to fire, then show the validation message since the field's content is invalid.

Does this explain my request more clearly?

**Comment by Albert-Gao** [comment]
I see. Sorry for the wrong interpretation.

If this field is critical for your submitting, then the validation should be trigger on `onBlur`, even with empty data, from the frontend.

For instance, on the registration page:
https://www.facebook.com/r.php?locale=en_GB&display=page

For that login, it doesn't trigger because the validation procedure is somehow different, the validation is from the backend rather than the frontend. Let's say you leave the username empty, and press the submit button, it will show an error message like this which is a validation message:

> The email address or phone number that you've entered doesn't match any account. Sign up for an account.

This is a normal validation message, it just checks whether this field matches the rule or not, rather than saying, `Please don't leave the field empty`.

Because they don't care if it's empty or not, this is a critical field, and it needs its data. And when they needs the data, you need the data to be validated.

And when `onBlur` has been triggered, which means the user tries to ignore this field, and this is something you don't want. So we need to notice the user :)

**Comment by Albert-Gao** [comment]
Furthermore, when you skip the validation when the field is empty and use `isFormOK` to control the state of submit button.

Then the user will be confused that why submit button is not enabled when there is no error :)

**Comment by JeremyColton** [comment]
I agree that the field should be validated in onBlur.  If the field's content is empty then the validation will fail and isFormOK will be false. But if the field's content is empty, don't show the validation message. the user can't click on the submit button because it's disabled as usual. I think this provides a nicer user-experience.

At least, could this feature be configurable (to show/hide validation message for empty fields) when setting up Veasy?

**Comment by Albert-Gao** [comment]
You can easily achieve that by modifying your binding of error text, if `value` from prop is empty or 0, then showing nothing, otherwise showing the error text from the `prop` :)

**Comment by JeremyColton** [comment]
Wonderful idea!!!!! Done!  Here's the interesting code update to the `<TextInput>` for anyone else who reads this:
```
        <div className="validation">
            <BaseInput
                autoComplete='new-password'
                type={type}
                name={name}
                className={value === '' ? 'ok' : status}
                placeholder={placeholder}
                onChange={onChange}
                disabled={disabled}
                value={value}
                ref={ref}
                maxLength={maxLength}
                id={id}
            />
            <p className={value === '' ? 'hidden' : (errorText === '' ? 'hidden' : '')}>{value ==='' ? '' : errorText}</p>
        </div>
```

**Comment by Albert-Gao** [comment]
Seems good, still stateless component :D Thanks for sharing the code
